const mongoose = require('mongoose')

// Constructer functions that generates new schema objects 
const Schema = mongoose.Schema;

const bookingSchema = new Schema({
    // _id are automatically generated by datbase as an objectID
    event: {
        type: Schema.Types.ObjectId,
        required: 'Event'
    },
    user: {
        type: Schema.Types.ObjectId,
        required: 'User'
    }
}, {timestamps: true}
);

module.exports = mongoose.model('Booking', bookingSchema)