const mongoose = require('mongoose')

// Constructer functions that generates new schema objects 
const Schema = mongoose.Schema;

const eventSchema = new Schema({
    // _id are automatically generated by datbase as an objectID
    title: {
        type: String,
        required: true
    },
    description: {
        type: String,
        required: true
    },
    price: {
        type: Number,
        required: true
    },
    date: {
        type: Date,
        required: true
    },
    creator: {
        type: Schema.Types.ObjectId,
        ref: "User"
    }
});

module.exports = mongoose.model('Event', eventSchema)