const mongoose = require('mongoose')

// Constructer functions that generates new schema objects 
const Schema = mongoose.Schema;

const eventSchema = new Schema({
    // _id are automatically generated by datbase
    title: {
        type: String,
        required: true
    },
    description: {
        type: String,
        required: true
    },
    price: {
        type: Number,
        required: true
    },
    date: {
        type: Date,
        required: true
    }
});
