const mongoose = require('mongoose')

// Constructer functions that generates new schema objects 
const Schema = mongoose.Schema;

const userSchema = new Schema({
    // _id are automatically generated by datbase as an objectID
    email: {
        type: String,
        required: true
    },
    password: {
        type: String,
        required: true
    },
    createdEvents: [
        {
          type: Schema.Types.ObjectId,
          ref: 'Event'
        }
    ]
});

module.exports = mongoose.model('User', userSchema)